### ISSUE TITLE
Laravel 10 et psr/http-message && psr/log

### ISSUE THREAD

**Issue by skudyfr** [wearestancer/lib-php#12]
Bonjour,
Possible de rendre compatible avec 
"psr/http-message": "^2.0",
"psr/log": "^3.0"
Car impossible de l'installer simplement avec composer lorsqu'on utilise Laravel 10.

**Comment by horgolzari98** [comment]
Bonjour !

Si vous rencontrez des problèmes d'installation de dépendances PSR comme "psr/http-message" et "psr/log" avec Composer lors de l'utilisation de Laravel 10, il est possible que Laravel 10 ait des contraintes de version spécifiques pour ces dépendances ou que d'autres packages que vous utilisez dans votre application Laravel imposent des versions particulières de ces dépendances.

Voici quelques étapes que vous pouvez suivre pour résoudre ce problème :

1. **Vérifiez les Exigences de Version dans Laravel 10 :**
   Assurez-vous de vérifier la documentation officielle de Laravel 10 et les fichiers `composer.json` dans votre projet pour voir s'il existe des contraintes de version spécifiques pour les dépendances PSR.

2. **Mises à Jour de Composer :**
   Assurez-vous d'utiliser une version récente de Composer. Vous pouvez mettre à jour Composer en exécutant la commande suivante dans votre terminal :
   ```bash
   composer self-update
   ```

3. **Versions Compatibles :**
   Si vous ne pouvez pas installer directement les versions spécifiées dans votre projet, essayez de trouver des versions compatibles qui satisfont à la fois les exigences de Laravel 10 et de vos autres dépendances.

4. **Vérifiez les Mises à Jour des Packages :**
   Assurez-vous que les autres packages que vous utilisez dans votre projet Laravel sont à jour. Certains packages peuvent exiger des versions spécifiques de certaines dépendances.

5. **Considérez les Alternatives :**
   Si les dépendances spécifiées posent toujours problème, vérifiez s'il existe des alternatives ou des packages similaires qui peuvent être utilisés avec Laravel 10 sans conflit.

6. **Problèmes Connus :**
   Recherchez des problèmes connus sur les dépôts GitHub des packages concernés, car parfois des problèmes spécifiques sont signalés et peuvent avoir des solutions ou des correctifs.

7. **Contactez les Auteurs des Packages :**
   Si tout échoue, il peut être utile de contacter les auteurs des packages qui posent problème pour obtenir des conseils spécifiques ou signaler le problème.

N'oubliez pas de sauvegarder votre fichier `composer.json` avant de faire des modifications importantes, et essayez de résoudre les conflits de versions de manière à ne pas perturber la stabilité de votre application Laravel.

Si vous avez des messages d'erreur spécifiques ou des exemples de ce qui ne fonctionne pas, n'hésitez pas à les partager pour obtenir une assistance plus précise.

**Comment by jdslv** [comment]
Bonjour,

Nous venons de mettre à jour les dépendances `psr/http-message` et `psr/log` sur la branche `main`. 

Une version arrive sous peu (après quelques tests supplémentaires).

**Comment by jdslv** [comment]
Bonjour,

On a été un peu plus long que prévu mais la version `v2.0.0` est disponible.
