### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by jackyhallyday** [wearestancer/lib-php#2]
Bonjour,
`composer require Stancer/lib-php`
renvoie :
```
In PackageDiscoveryTrait.php line 364:
                                                                                                                                                                          
  Could not find a matching version of package Stancer/lib-php. Check the package spelling, your version constraint and that the package is available in a stability whi  
  ch matches your minimum-stability (stable).
```

Idem avec une minimum-stability définie en tant que "dev".

**Comment by jackyhallyday** [comment]
Note pour les autres utilisateurs, la commande composer correcte est :
`composer require stancer/stancer`

**Comment by bennukem** [comment]
J'ai trouvé sur : 
 composer require stancer/stancer

**Comment by jackyhallyday** [comment]
> J'ai trouvé sur : composer require stancer/stancer

Mais ce qui s’y trouve est inutilisable, non ? Ou bien c’est parce que je suis en 8.2-dev, mais vu la nature des bugs, je ne pense pas que c’est le problème…

**Comment by bennukem** [comment]
Quels bugs ?
Je n'ai pas encore utilisé la lib. J'attends que Stancer accepte d'autres currencies avant de vraiment m'y intéresser

**Comment by jackyhallyday** [comment]
Il y en a tellement... j'ai arrêté les rapports quand j'ai vu l'état de l'API (trouvée sur stancer/stancer) et de la doc.
Par exemple sur l'accueil GitHub, il y a des exemples avec :
`Stancer\Api\Config::init($key);`
Mais il n'y a pas de classe Stancer\Api. Dans la doc sur stancer.com (https://www.stancer.com/documentation/fr/api/?lang=php) c'est 
`Stancer\Config::init(['<your_public_keys>', '<your_secret_keys>']);`
Du coup il semble que ce GitHub (mais c'est pareil pour GitLab) est dépassé.

Les bugs démarrent dès que tu essayes d'instancier quoi que ce soit.
Ça passe par un objet commun qui fait une comparaison entre le type de ce qui lui est transmit, et le nom d'une classe. Sauf que tout y passe, y compris de simples interger, float, bool, string. Du coup ça plante : "classe inconnue".
Et quand tu fais un patch "pour voir", d'autres choses plantent derrière avec par exemple une classe d'exception introuvable : Stancer\Exceptions\InvalidCvcException. Dans les fichiers source, on trouve Stancer\Exceptions\InvalidCvcException.

Bref, on dirait qu'il y a un mélange de code avant/après un refactoring ou je ne sais quoi, mais en tout cas, ça me parait inutilisable.

**Comment by bennukem** [comment]
Le namespace semble être seulement Stancer et non Stancer\Api\xxxx

Mais sinon c'est sûr que la doc ne brille pas, pour un truc tout juste sorti.

**Comment by Allinou** [comment]
Même constat que [jackyhallyday], ça n'est pas utilisable en l'état. 
Documentation qui n'est pas en adéquation ni pour l'installation, ni pour l'implémenation. 
J'ai pris contact par mail avec le support pour avoir une date pour ne pas perdre de temps. 
Ca ne fait pas très sérieux. La moindre des choses serait de mettre un message pour préciser "INUTILISABLE" ou encore mieux de ne pas diffuser en l'état.

**Comment by bennukem** [comment]
C'est sûr que pour un truc juste sorti, ça fait pas bien sérieux.
Il attendent peut être qu'une bonne âme fasse le taff.

**Comment by aeris** [comment]
Effectivement, le readme pointait encore sur l’ancien nom de package.
C’est corrigé du coup ! :blush:
