### ISSUE TITLE
Missing Payouts ?

### ISSUE THREAD

**Issue by rycks** [wearestancer/lib-php#5]
Hello,

There is only cURL example on documentation (https://www.stancer.com/documentation/fr/api/?lang=php#payouts) and no Payout(s) object in php-lib sources ... did you plan to add it or do we have to make raw requests to fetch informations about that ?

**Comment by jdslv** [comment]
Hello, 

I forgot it, sorry 

It will be in the next release ([the code is available in GitLab](https://gitlab.com/wearestancer/library/lib-php/-/merge_requests/5))

**Comment by jdslv** [comment]
`v1.1.0` released
