### ISSUE TITLE
payout php lib vs online doc ...

### ISSUE THREAD

**Issue by rycks** [wearestancer/lib-php#6]
Hello @jdslv 
thanks for last update about payout, but there is something not clear with documentation:

https://www.stancer.com/documentation/fr/api/?lang=php#payouts

what about that fields in your lib ?

- payments
- refunds
- disputes
- statement_description

thanks

**Comment by rycks** [comment]
thanks to slack support online doc is the reference

**Comment by jdslv** [comment]
Hello @rycks 

For `statement_description`, you can get it with, depending the way you desire to write your code:
- with a camel case method `$payout->getStatementDescription()`
- with a camel case property `$payout->statementDescription`
- with a snake case method `$payout->get_statement_description()`
- with a snake case property `$payout->statement_description`

Nota: everything is massively aliased to allow you to write code as you wanted (but I just realize that I forgot to add snake case versions to the PHPDoc)

For the payments, refunds and disputes data, it will be a little different from the API documentation. 
You need to use `details` property (or `getMethod()` method), then access to `payments`/`refunds`/`disputes` property (or `getPayments`/... methods).

I will only be talking about `payments` to simplify, but every works with `refunds` and `disputes`

To obtain the total amount, you only need to 
```php
$totalPaymentsAmount = $payout->getDetails()->getPayments()->getAmount();
$totalPaymentsCurrency = $payout->getDetails()->getPayments()->getCurrency();

// or 

$totalPaymentsAmount = $payout->details->payments->amount;
$totalPaymentsCurrency = $payout->details->payments->currency;
```

You can also list every `payments` in the `disputes`. It will return you a generator, fetching every payments in batch.

```php
foreach ($payout->details->payments() as $payment) {
    // do something with `$payment`
}

// or, maybe a more explicite method

foreach ($payout->details->listPayments() as $payment) {
    // do something with `$payment`
}
```
